# Generated by Django 4.1.1 on 2022-09-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBC',
            fields=[
                ('id_dbc', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id_rowDBC')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование компонента')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('id_unit', models.IntegerField(verbose_name='id_ед.изм.')),
                ('min_rezerve', models.IntegerField(verbose_name='Мин.кол.на складе')),
                ('articul_1C', models.CharField(blank=True, max_length=20, verbose_name='Артикул 1С')),
                ('code_1C', models.CharField(blank=True, max_length=20, verbose_name='Код 1С')),
                ('name_1C', models.CharField(blank=True, max_length=150, verbose_name='Наименование 1С')),
                ('id_parent', models.IntegerField(verbose_name='id_Родительская группа')),
                ('id_lvl', models.IntegerField(blank=True, verbose_name='id_резерв')),
            ],
        ),
        migrations.CreateModel(
            name='DBE',
            fields=[
                ('id_dbe', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id_rowDBE')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата расхода')),
                ('id_component', models.IntegerField(verbose_name='id_компонент')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('comments', models.CharField(blank=True, max_length=150, verbose_name='комментарии')),
            ],
        ),
        migrations.CreateModel(
            name='DBGC',
            fields=[
                ('id_dbgc', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id_rowDBGC')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование группы')),
                ('id_parent', models.IntegerField(verbose_name='id_Родительская группа')),
            ],
        ),
        migrations.CreateModel(
            name='DBI',
            fields=[
                ('id_dbi', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id_rowDBI')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата прихода')),
                ('id_component', models.IntegerField(verbose_name='id_компонент')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('comments', models.CharField(blank=True, max_length=150, verbose_name='комментарии')),
            ],
        ),
        migrations.CreateModel(
            name='DBU',
            fields=[
                ('id_dbu', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id_rowDBU')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование ед.изм')),
            ],
        ),
    ]
