# Generated by Django 4.0.6 on 2022-09-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsklad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbc',
            name='id_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dsklad.dbgc', verbose_name='родительская группа'),
        ),
        migrations.AlterField(
            model_name='dbc',
            name='id_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dsklad.dbu', verbose_name='ед.изм.'),
        ),
        migrations.AlterField(
            model_name='dbi',
            name='id_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dsklad.dbc', verbose_name='наименование компонента'),
        ),
    ]
