# Generated by Django 4.0.6 on 2022-09-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsklad', '0002_alter_dbc_id_parent_alter_dbc_id_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbgc',
            name='id_parent',
            field=models.IntegerField(null=True, verbose_name='id_Родительская группа'),
        ),
    ]
