# Generated by Django 4.0.6 on 2022-09-24 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsklad', '0003_alter_dbgc_id_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbgc',
            name='id_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dsklad.dbgc', verbose_name='id_Родительская группа'),
        ),
    ]
